USE [db_siriluk_shop]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.smGoods') AND Type = N'U')
BEGIN
CREATE TABLE [dbo].[smGoods](
	[GoodsID] VARCHAR(50) PRIMARY KEY NOT NULL,
	[GoodsNo] VARCHAR(50) NOT NULL,
	[GoodsBarcode] VARCHAR(20) NULL,
	[GoodsName] VARCHAR(255) NOT NULL,
	[GoodsQty] DECIMAL(20,2) NOT NULL,
	[GoodsPrice] DECIMAL(20,2) NOT NULL,
	[GoodsCost] DECIMAL(20,2) NULL,
	[GoodsUnitID] VARCHAR(50) NOT NULL,
	[GoodsUnitName] VARCHAR(255) NOT NULL,
	[GoodsLocationID] VARCHAR(50) NULL,
	[GoodsLocationName] VARCHAR(50) NULL,
	[CreatedBy] VARCHAR(50) DEFAULT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] VARCHAR(50) DEFAULT NULL,
	[ModifiedDate] DATETIME NOT NULL,
	[IsDelete] BIT NOT NULL
)
END
GO

IF NOT EXISTS(SELECT 1 FROM sys.Objects WHERE  Object_id = OBJECT_ID(N'dbo.smUnit') AND Type = N'U')
BEGIN
CREATE TABLE [dbo].[smUnit](
	[UnitID] VARCHAR(50) PRIMARY KEY NOT NULL,
	[UnitNo] VARCHAR(50) NOT NULL,
	[UnitName] VARCHAR(255) NOT NULL,
	[UnitQty] DECIMAL(20,2) NOT NULL,
	[CreatedBy] VARCHAR(50) NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] VARCHAR(50) DEFAULT NULL,
	[ModifiedDate] DATETIME NOT NULL,
	[IsDelete] BIT NOT NULL
)
END
GO
